id: A8E311311
title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:31:39.488313
  last_modified_at: 2022-03-01 06:31:39.488336
