id: A8E311311
title: Daily Practice of Dorje Gotrab
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:31:39.486782
  last_modified_at: 2022-03-01 06:31:39.486789
